### ISSUE TITLE
Full book outline

### ISSUE THREAD

**Issue by datalorax** [datalorax/sds-r#25]
I think we're at the point where we can fairly safely create a full book outline. It's starting to get messy in terms of organization without it. Once we get that, we may want to go ahead and create empty Rmd's with just the headers for each chapter, then we can look at #24 a bit easier. I'd like to have four sections: Foundations, Data Visualization, Functional Programming, and Machine Learning. Then probably 10-ish chapters in each section.

I can draft an outline sometime in the next few days, but if either of you feel up for taking the first crack at it, that would be great. As I've mentioned before, I basically just want to mirror the courses.

**Comment by ohmaddi** [comment]
Daniel, this is a great idea and it would help organize work better and know our next steps. I can take the first crack at it. Does that mean I can change the numbers of the current chapters?

**Comment by datalorax** [comment]
Sure. I was thinking we might even want to name them with sections. For example, the machine learning stuff would all be the fourth section, so those chapters could be 401, 402, etc.

**Comment by ohmaddi** [comment]
I see - so you are suggesting 401 instead of 4.1. It can be a good idea, we should try it out.

**Comment by datalorax** [comment]
Yeah I'm just generally not really a fan of periods in file names. What if we get the outline together first and then we can create the files after that?

**Comment by ohmaddi** [comment]
Yes, lets do that here and let me know if that's what you were thinking about: 

**1 Foundations**

- 401 Getting Started
- 402 R Markdown 
- 403 Applied example 
- 404 Basic plotting 
- 405 Data structures & Data types
- 406 Data structures, classes, and routine functions
- 407 Functions,
- 408 Loops
- 409 Data restructuring
- 410 Advanced plotting with base graphics

**2 Data Visualization**
401
402
403
404
405
406
407
408
409
410

**3 Functional Programming**
401
402
403
404
405
406
407
408
409
410

**4 Machine Learning**
401 
402
403
404
405
406
407
408
409
410

I could not find the repo of Data vis term and functional programming from your profile. Could you please share them to fill out section 2 ans3.

**Comment by datalorax** [comment]
Yes, the courses should be here: https://github.com/uo-datasci-specialization

Also, I think you might have been looking at an old course I taught for the foundations part. I don't think it's really worth covering things like advanced plotting with base (we'll just use ggplot throughout). And functions and loops can probably wait until the third section.

In terms of chapter numbers, I was thinking more 101, 102... for section 1, the 201, 202... for section 2, etc.

**Comment by datalorax** [comment]
Also, just looking at the topics for Course 1 (https://github.com/uo-datasci-specialization/c1-intro_data_sci) it may be that the first section has fewer chapters. Maybe more like 6-8 instead of 10. I think we can hold off on creating chapters about papaja, for example. While I think that's helpful, it's not really *foundational*.

**Comment by ohmaddi** [comment]
Yes sorry about the 401 I started with the machine learning section and copied pasted without paying the attention to the numbers. I will update the outline.

**Comment by ohmaddi** [comment]
Here is a first attempt at book outline:

> Preface - Why R?

1 Foundations

> 101 Getting Started
> 102 Producing your first plot
> 103 Basic R Markdown
> 104 Basic data wrangling 
> 105 ~~Data structures~~  Types of data
> 106 Tidy data
> 107 Joins
> 108 Collaborating with git and GitHub
> 109 A collaborative exploratory data analysis example

2 Data Visualization

> 201 Introduction to visualizations
> 202 Visual perception ~~Joins~~ **DA: Move to foundations**
> 203 Color
> 204 Refining your plots ~~Communication~~
> 205 Geographic data
> 206 Visualizing uncertainty
> 207 Tables & fonts
> 208 Websites in R Markdown
> 209 Flex dashboards
> 210 Shiny

3 Functional Programming

> 301 Data Types
> 302 Iteration
> 303 Batch load and processing data
> 304 List columns
> 305 Parallel iterations
> 306 Writing functions
> 307 Package development

4 Machine Learning
> 401 Inference vs. Prediction
> 402 Ethics in Machine Learning
> 403 Train and Test Splits *k*-fold CV
> 404 Extending `lm`: Ridge, Lasso, Elastic net
> 405 Feature engineering
> 406 *K*-nearest neighbor
> 407 Decision trees
> 408 Bagged trees **& Random forests**
> ~~409 Random forests~~
> 409 Boosted Trees
> 411 ~~Intro to neural nets with Keras & Tensorflow~~ **DA: We can maybe do this one but I'm not super confident in my knowledge here**

**Comment by datalorax** [comment]
Thanks Ouafaa! I think this looks great. After class, I will try to review it a little more in-depth and then we can get it finalized.

**Comment by ohmaddi** [comment]
Perfect - Thanks Daniel!

**Comment by datalorax** [comment]
Okay, I just edited it some. Let me know what you think! @brendanhcullen, if you want to take a look too, that would be great.

**Comment by ohmaddi** [comment]
Thanks for the edits, Daniel!

**Comment by datalorax** [comment]
Okay, I'm going to move this to GitHub Projects. I think we should treat this as a general guide but then be flexible with it in terms of collapsing or expanding chapters as we go.

**Comment by datalorax** [comment]
Alright, I'm closing this for now. I just made two projects for us, one related to this outline, and the other related to non-writing activities. See https://github.com/datalorax/sds-r/projects/1

**Comment by brendanhcullen** [comment]
@datalorax @ohmaddi Sorry I'm behind on this y'all! I think this is looking really good. The only real note I have is that a few topics might be a little too big and out of scope -- namely 

> 108 Collaborating with git and GitHub
> 208 Websites in R Markdown
> 209 Flex dashboards
> 210 Shiny

These topics are rather complex in their own right and, while they are all generally extremely useful, are perhaps a bit beyond the "foundations" of social data science, and it seems like they wouldn't necessarily build cumulatively toward later topics in the book. That being said, there might be a way to incorporate some really minimal examples that tie in well to topics that are previously covered (e.g. demonstrating how to group a series of data visualizations shown in Section 2 together in a website, flex dashboard, and shiny app). Just food for thought!

**Comment by datalorax** [comment]
Thanks Brendan,

Those are all definitely *huge* topics. But, I also think they are important to cover. We just might need more than one chapter on them and we'll definitely want to qualify that the content in the chapter is only an introduction.

If you recall, the second course is supposed to be about data visualization and communication, including mediums for presentation. So that's why I think websites, dashboards, and shiny fit in there. They should all be "getting started" type chapters, but I do view that as pretty important content (particularly if, say, you want to develop a portfolio as you go hunting for a job).

In terms of collaborating with git and GitHub, that is a topic we cover in the first course and I do think it's foundational to data science if you're going to be working in teams at all. We probably need more than one chapter, and we'll probably need to qualify it as mostly an introduction, but I think it's important to cover. So I think we should try, and we'll see how it goes as we get writing it.

**Comment by brendanhcullen** [comment]
@datalorax all great points! on second thought, it is certainly true that working with version control and communication platforms like shiny, websites, etc. are in fact foundational to social data science (and data science more broadly) since data scientists don't live in silos (quite the opposite) 🙃 It will be a fun challenge to find a way to give a concise yet thorough intro to these topics, but I think we can do it!
