### ISSUE TITLE
Package for the book

### ISSUE THREAD

**Issue by datalorax** [datalorax/sds-r#26]
@brendanhcullen I know you already started on the package for learnr tutorials. I think we need a standalone package for the book. It could be the one you started, or we could start a new one and port what you have in that over. The only reason I think the latter might be a better idea is just because then we could have the package name be *sds* or *sdsr* to match the book title.

The main reason I think we want a package for the book is because (a) we can create our own themes for different types of plots that we use throughout the book, and (b) we can use it as a way to share data, so they don't have to clone the repo or something to get the data. Incorporating the learnr tutorials there also makes sense.

Happy to start this or work from what you have, Brendan. Let me know what you each think.

**Comment by brendanhcullen** [comment]
@datalorax Totally happy to try this out! The reason I created a separate package for the learnr apps is that Desirée recommended it (more info [here](https://desiree.rbind.io/post/2020/learnr-iframes/) + screenshot below of her recommended workflow). I'm actually gonna chat with her tomorrow so I can ask her about this. But I think having a package for the book is a good idea either way. If you want to create the file structure we will need for a package, I can test out adding an example learnr app in a separate branch. 

![Screen Shot 2020-11-09 at 9 35 14 AM](https://user-images.githubusercontent.com/32279312/98576078-e04fb880-226e-11eb-8551-af5b534c41c5.png)

**Comment by datalorax** [comment]
Okay, great! I'll try to get a basic package infrastructure up there today. Will come comment on this issue when it's up.

**Comment by datalorax** [comment]
Closing this because it's now setup [here](https://github.com/datalorax/sds-pkg)
