### ISSUE TITLE
Taking out time-intensive chunks

### ISSUE THREAD

**Issue by datalorax** [datalorax/sds-r#39]
I think we should basically manually cache a lot of the big chunks. Here's how I did it with the boosted trees chapter (which I'll be pushing tonight - it's done but I'm having issues with other finicky things I was trying to clean up). 

![Screen Shot 2020-12-04 at 8 24 26 PM](https://user-images.githubusercontent.com/10944136/101713681-f78bec80-3a4c-11eb-883e-1e298e71c1bc.png)

Basically we'll have a new folder called "models" (which will also be up there after I push the boosted tree stuff) and then we just save the models after we run them there. Then we only echo the code that shows the model running, and eval (but don't echo) the code that reads the model in. This is way faster and will help our build time a lot. If we don't do this, I don't know if there is a way to get the book to build with the cache without committing it which I *really* don't want to do.

I can try to submit a new PR for this probably later tonight or maybe tomorrow.

**Comment by brendanhcullen** [comment]
Good idea @datalorax!

**Comment by datalorax** [comment]
Addressed by 7cac6d939da0d56e802a628adfe0e72c72584c4b
